version: "3"
services:
  # build minimal
  build-minimal:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make build

  build-minimal-release:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make build-release

  run-minimal:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make run

  run-minimal-release:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make run-release