version: "3"
services:
  # build minimal
  build-minimal:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make build

  # TODO: X11 forwarding
  run-minimal:
    build: .
    volumes:
      - ./:/work
    working_dir: /work/minimal
    command: make run
