name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-minimal:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2     
      with:
        submodules: true              
    - name: build debug
      run: docker-compose run build-minimal